# ====================================
# ASTRO SESSION ANALYSER - EXAMPLE CONFIG
# Complete configuration template with all supported parameters
# ====================================

# Discord webhook URL for sending summaries (REQUIRED)
webhook: "https://discord.com/api/webhooks/example/test"

# Time window in hours to analyze sessions
hours: 48

# Path to Ekos analyze files 
# Default paths:
#   - Native KStars: ~/.local/share/kstars/analyze
#   - Flatpak KStars: ~/.var/app/org.kde.kstars/data/kstars/analyze
analyze_dir: "/home/grm/.var/app/org.kde.kstars/data/kstars/analyze"

# Basic log level (DEBUG, INFO, WARNING, ERROR)
log_level: "INFO"

# ====================================
# REPORTING CONFIGURATION
# ====================================

# Discord report level: minimal, standard, detailed
# - minimal: Ultra-quick notifications with conditions & autofocus
# - standard: Current balanced format (default) 
# - detailed: Comprehensive analysis with correlations (auto-enables advanced analytics)
discord_report_level: "standard"

# ====================================
# PLOTTING CONFIGURATION
# ====================================

# Enable temporal plotting
plotting:
  enabled: true
  output_dir: "./plots"
  # Keep plots after dry-run for inspection (optional)
  cleanup_after_dry_run: true

# ====================================
# ALERT THRESHOLDS
# ====================================

# Automatic alert thresholds
alert_thresholds:
  # HFR drift warning (pixels)
  hfr_drift_warning: 0.5
  
  # Temperature swing warning (°C)
  temperature_swing_warning: 5.0
  
  # Success rate warning (0.0-1.0)
  success_rate_warning: 0.8
  
  # Minimum stars for quality warning
  min_stars_warning: 100

# ====================================
# NOTIFICATION PREFERENCES
# ====================================

notifications:
  # Send alerts for poor performance
  performance_alerts: true
  
  # Send summary only if captures > threshold
  min_captures_for_report: 1
  
  # Include quality score in reports (requires advanced_analytics)
  include_quality_score: true

# ====================================
# ADVANCED ANALYTICS (for detailed level)
# Automatically enabled for 'detailed' level
# Requires: pip install numpy scipy
# ====================================

# Analytics are automatically enabled for detailed level
# No need to configure - everything is included in detailed mode

# ====================================
# QUICK MODE EXAMPLES
# ====================================

# To switch quickly between modes:

# MINIMAL MODE (quick notifications):
# discord_report_level: "minimal"

# STANDARD MODE (balanced):
# discord_report_level: "standard" 

# DETAILED MODE (comprehensive analysis with correlations):
# discord_report_level: "detailed"
